package de.greenrobot.daoexample;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table AMERICAN_NEIGHBOUR.
 */
public class AmericanNeighbour {

    private Long id;
    private Integer channel_id;
    private String request_url;
    private String reponse;
    private Integer list_index;
    private Integer update_time;
    private Integer operation_type;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public AmericanNeighbour() {
    }

    public AmericanNeighbour(Long id) {
        this.id = id;
    }

    public AmericanNeighbour(Long id, Integer channel_id, String request_url, String reponse, Integer list_index, Integer update_time, Integer operation_type) {
        this.id = id;
        this.channel_id = channel_id;
        this.request_url = request_url;
        this.reponse = reponse;
        this.list_index = list_index;
        this.update_time = update_time;
        this.operation_type = operation_type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getChannel_id() {
        return channel_id;
    }

    public void setChannel_id(Integer channel_id) {
        this.channel_id = channel_id;
    }

    public String getRequest_url() {
        return request_url;
    }

    public void setRequest_url(String request_url) {
        this.request_url = request_url;
    }

    public String getReponse() {
        return reponse;
    }

    public void setReponse(String reponse) {
        this.reponse = reponse;
    }

    public Integer getList_index() {
        return list_index;
    }

    public void setList_index(Integer list_index) {
        this.list_index = list_index;
    }

    public Integer getUpdate_time() {
        return update_time;
    }

    public void setUpdate_time(Integer update_time) {
        this.update_time = update_time;
    }

    public Integer getOperation_type() {
        return operation_type;
    }

    public void setOperation_type(Integer operation_type) {
        this.operation_type = operation_type;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
