package de.greenrobot.daoexample;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table LOCAL_MEDIA.
 */
public class LocalMedia {

    private Long id;
    private String dir;
    private String file;
    private Integer size;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public LocalMedia() {
    }

    public LocalMedia(Long id) {
        this.id = id;
    }

    public LocalMedia(Long id, String dir, String file, Integer size) {
        this.id = id;
        this.dir = dir;
        this.file = file;
        this.size = size;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDir() {
        return dir;
    }

    public void setDir(String dir) {
        this.dir = dir;
    }

    public String getFile() {
        return file;
    }

    public void setFile(String file) {
        this.file = file;
    }

    public Integer getSize() {
        return size;
    }

    public void setSize(Integer size) {
        this.size = size;
    }

    // KEEP METHODS - put your custom methods here
    private void keep() {

    }
    // KEEP METHODS END

}
