package de.greenrobot.daoexample;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LOCAL_PLAY_HISTORY.
 */
public class LocalPlayHistory {

    private Long id;
    private String videoTitle;
    private String playedTime;
    private Integer tvLength;
    private String lastWatchTime;
    private String localUrl;

    public LocalPlayHistory() {
    }

    public LocalPlayHistory(Long id) {
        this.id = id;
    }

    public LocalPlayHistory(Long id, String videoTitle, String playedTime, Integer tvLength, String lastWatchTime, String localUrl) {
        this.id = id;
        this.videoTitle = videoTitle;
        this.playedTime = playedTime;
        this.tvLength = tvLength;
        this.lastWatchTime = lastWatchTime;
        this.localUrl = localUrl;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getVideoTitle() {
        return videoTitle;
    }

    public void setVideoTitle(String videoTitle) {
        this.videoTitle = videoTitle;
    }

    public String getPlayedTime() {
        return playedTime;
    }

    public void setPlayedTime(String playedTime) {
        this.playedTime = playedTime;
    }

    public Integer getTvLength() {
        return tvLength;
    }

    public void setTvLength(Integer tvLength) {
        this.tvLength = tvLength;
    }

    public String getLastWatchTime() {
        return lastWatchTime;
    }

    public void setLastWatchTime(String lastWatchTime) {
        this.lastWatchTime = lastWatchTime;
    }

    public String getLocalUrl() {
        return localUrl;
    }

    public void setLocalUrl(String localUrl) {
        this.localUrl = localUrl;
    }

}
