package de.greenrobot.daoexample;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table PLAY_HISTORY.
 */
public class PlayHistory {

    private Long id;
    private String playId;
    private String subjectId;
    private String videoTitle;
    private String playedTime;
    private String clientType;
    private String definition;
    private String episode;
    private String picPath;
    private String categoryId;
    private Integer tvLength;
    private Integer isSynchronized;
    private String albumName;
    private Integer nextplayId;
    private String lastWatchTime;
    private String passport;
    private String localUrl;
    private Integer tvisfee;
    private Integer real_playorder;
    private Integer site;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public PlayHistory() {
    }

    public PlayHistory(Long id) {
        this.id = id;
    }

    public PlayHistory(Long id, String playId, String subjectId, String videoTitle, String playedTime, String clientType, String definition, String episode, String picPath, String categoryId, Integer tvLength, Integer isSynchronized, String albumName, Integer nextplayId, String lastWatchTime, String passport, String localUrl, Integer tvisfee, Integer real_playorder, Integer site) {
        this.id = id;
        this.playId = playId;
        this.subjectId = subjectId;
        this.videoTitle = videoTitle;
        this.playedTime = playedTime;
        this.clientType = clientType;
        this.definition = definition;
        this.episode = episode;
        this.picPath = picPath;
        this.categoryId = categoryId;
        this.tvLength = tvLength;
        this.isSynchronized = isSynchronized;
        this.albumName = albumName;
        this.nextplayId = nextplayId;
        this.lastWatchTime = lastWatchTime;
        this.passport = passport;
        this.localUrl = localUrl;
        this.tvisfee = tvisfee;
        this.real_playorder = real_playorder;
        this.site = site;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPlayId() {
        return playId;
    }

    public void setPlayId(String playId) {
        this.playId = playId;
    }

    public String getSubjectId() {
        return subjectId;
    }

    public void setSubjectId(String subjectId) {
        this.subjectId = subjectId;
    }

    public String getVideoTitle() {
        return videoTitle;
    }

    public void setVideoTitle(String videoTitle) {
        this.videoTitle = videoTitle;
    }

    public String getPlayedTime() {
        return playedTime;
    }

    public void setPlayedTime(String playedTime) {
        this.playedTime = playedTime;
    }

    public String getClientType() {
        return clientType;
    }

    public void setClientType(String clientType) {
        this.clientType = clientType;
    }

    public String getDefinition() {
        return definition;
    }

    public void setDefinition(String definition) {
        this.definition = definition;
    }

    public String getEpisode() {
        return episode;
    }

    public void setEpisode(String episode) {
        this.episode = episode;
    }

    public String getPicPath() {
        return picPath;
    }

    public void setPicPath(String picPath) {
        this.picPath = picPath;
    }

    public String getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId;
    }

    public Integer getTvLength() {
        return tvLength;
    }

    public void setTvLength(Integer tvLength) {
        this.tvLength = tvLength;
    }

    public Integer getIsSynchronized() {
        return isSynchronized;
    }

    public void setIsSynchronized(Integer isSynchronized) {
        this.isSynchronized = isSynchronized;
    }

    public String getAlbumName() {
        return albumName;
    }

    public void setAlbumName(String albumName) {
        this.albumName = albumName;
    }

    public Integer getNextplayId() {
        return nextplayId;
    }

    public void setNextplayId(Integer nextplayId) {
        this.nextplayId = nextplayId;
    }

    public String getLastWatchTime() {
        return lastWatchTime;
    }

    public void setLastWatchTime(String lastWatchTime) {
        this.lastWatchTime = lastWatchTime;
    }

    public String getPassport() {
        return passport;
    }

    public void setPassport(String passport) {
        this.passport = passport;
    }

    public String getLocalUrl() {
        return localUrl;
    }

    public void setLocalUrl(String localUrl) {
        this.localUrl = localUrl;
    }

    public Integer getTvisfee() {
        return tvisfee;
    }

    public void setTvisfee(Integer tvisfee) {
        this.tvisfee = tvisfee;
    }

    public Integer getReal_playorder() {
        return real_playorder;
    }

    public void setReal_playorder(Integer real_playorder) {
        this.real_playorder = real_playorder;
    }

    public Integer getSite() {
        return site;
    }

    public void setSite(Integer site) {
        this.site = site;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
